name: NodeJS Github Action

on:
  push:
    branches:
      - dev-team

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

      - name: Notify Slack Action
       uses: ravsamhq/notify-slack-action@2.3.0
       if: always()
       with: 
         status: ${{ job.status }}
         notify_when: 'failure'
         notification_title: '{workflow} has {status_message}'
         message_format: '{emoji} *{workflow} {status_message} in <{repo_url}|{repo}>'
         footer: 'Linked to Repo <{repo_url}|{repo}>'
         notify_when: 'failure'
         mention_users: 'dev'
         mention_users_when: 'failure, warnings'
         mention_groups: 'dev'
         mention_groups_when: 'failure,warmings'

       env:
          SLACK_WEBHOOH_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROUKU_API_KEY}}
          heroku_app_name: "github-actions-node" # Must be unique in Heroku
          heroku_email: "temmy.tech01@outlook.com"
